/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 10:46:16 GMT 2019
 */

package sortpom.wrapper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jdom.Element;
import org.junit.runner.RunWith;
import sortpom.parameter.PluginParameters;
import sortpom.wrapper.ElementSortOrderMap;
import sortpom.wrapper.ElementWrapperCreator;
import sortpom.wrapper.content.Wrapper;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ElementWrapperCreator_ESTest extends ElementWrapperCreator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      ElementWrapperCreator elementWrapperCreator0 = new ElementWrapperCreator(elementSortOrderMap0);
      PluginParameters pluginParameters0 = mock(PluginParameters.class, new ViolatedAssumptionAnswer());
      elementWrapperCreator0.setup(pluginParameters0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      ElementWrapperCreator elementWrapperCreator0 = new ElementWrapperCreator(elementSortOrderMap0);
      Element element0 = new Element("modules", "modules");
      Wrapper<Element> wrapper0 = elementWrapperCreator0.createWrapper(element0);
      assertFalse(wrapper0.isSortable());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      ElementWrapperCreator elementWrapperCreator0 = new ElementWrapperCreator(elementSortOrderMap0);
      elementSortOrderMap0.addElement((Element) null, 312);
      // Undeclared exception!
      try { 
        elementWrapperCreator0.createWrapper((Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.ElementWrapperCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      ElementWrapperCreator elementWrapperCreator0 = new ElementWrapperCreator(elementSortOrderMap0);
      Wrapper<Element> wrapper0 = elementWrapperCreator0.createWrapper((Element) null);
      assertFalse(wrapper0.isContentElement());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      ElementWrapperCreator elementWrapperCreator0 = new ElementWrapperCreator(elementSortOrderMap0);
      // Undeclared exception!
      try { 
        elementWrapperCreator0.setup((PluginParameters) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.ElementWrapperCreator", e);
      }
  }
}
