/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:07:19 GMT 2019
 */

package sortpom.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayOutputStream;
import java.io.FilterOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.junit.runner.RunWith;
import sortpom.util.BufferedLineSeparatorOutputStream;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BufferedLineSeparatorOutputStream_ESTest extends BufferedLineSeparatorOutputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BufferedLineSeparatorOutputStream bufferedLineSeparatorOutputStream0 = new BufferedLineSeparatorOutputStream("", (OutputStream) null);
      byte[] byteArray0 = new byte[7];
      byteArray0[1] = (byte)54;
      bufferedLineSeparatorOutputStream0.write(byteArray0, 0, 3);
      assertArrayEquals(new byte[] {(byte)0, (byte)54, (byte)0, (byte)0, (byte)0, (byte)0, (byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream(0);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(byteArrayOutputStream0);
      BufferedLineSeparatorOutputStream bufferedLineSeparatorOutputStream0 = new BufferedLineSeparatorOutputStream("c:)K_3", objectOutputStream0);
      bufferedLineSeparatorOutputStream0.write(0);
      bufferedLineSeparatorOutputStream0.close();
      assertEquals(7, byteArrayOutputStream0.size());
      assertEquals("\u00AC\u00ED\u0000\u0005w\u0001\u0000", byteArrayOutputStream0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BufferedLineSeparatorOutputStream bufferedLineSeparatorOutputStream0 = new BufferedLineSeparatorOutputStream("(-", (OutputStream) null);
      byte[] byteArray0 = new byte[8];
      byteArray0[1] = (byte)10;
      bufferedLineSeparatorOutputStream0.write(byteArray0, 1, (int) (byte)1);
      // Undeclared exception!
      try { 
        bufferedLineSeparatorOutputStream0.write(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.util.BufferedLineSeparatorOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("Cn*}", false);
      FilterOutputStream filterOutputStream0 = new FilterOutputStream(mockFileOutputStream0);
      filterOutputStream0.close();
      BufferedLineSeparatorOutputStream bufferedLineSeparatorOutputStream0 = new BufferedLineSeparatorOutputStream("Jx0bfip]5r P", filterOutputStream0);
      bufferedLineSeparatorOutputStream0.write((-54));
      try { 
        bufferedLineSeparatorOutputStream0.close();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      BufferedLineSeparatorOutputStream bufferedLineSeparatorOutputStream0 = null;
      try {
        bufferedLineSeparatorOutputStream0 = new BufferedLineSeparatorOutputStream((String) null, (OutputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.util.BufferedLineSeparatorOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      BufferedLineSeparatorOutputStream bufferedLineSeparatorOutputStream0 = new BufferedLineSeparatorOutputStream("", (OutputStream) null);
      bufferedLineSeparatorOutputStream0.write(0);
      // Undeclared exception!
      try { 
        bufferedLineSeparatorOutputStream0.close();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.util.BufferedLineSeparatorOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      BufferedLineSeparatorOutputStream bufferedLineSeparatorOutputStream0 = new BufferedLineSeparatorOutputStream("", (OutputStream) null);
      byte[] byteArray0 = new byte[8];
      byteArray0[1] = (byte)10;
      bufferedLineSeparatorOutputStream0.write(byteArray0, 1, (int) (byte)1);
      bufferedLineSeparatorOutputStream0.write(0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      BufferedLineSeparatorOutputStream bufferedLineSeparatorOutputStream0 = new BufferedLineSeparatorOutputStream("", (OutputStream) null);
      bufferedLineSeparatorOutputStream0.clearLineBuffer();
  }
}
