/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:03:00 GMT 2019
 */

package sortpom;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jdom.Document;
import org.junit.runner.RunWith;
import sortpom.XmlOutputGenerator;
import sortpom.parameter.PluginParameters;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlOutputGenerator_ESTest extends XmlOutputGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlOutputGenerator xmlOutputGenerator0 = new XmlOutputGenerator();
      // Undeclared exception!
      try { 
        xmlOutputGenerator0.setup((PluginParameters) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.XmlOutputGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XmlOutputGenerator xmlOutputGenerator0 = new XmlOutputGenerator();
      // Undeclared exception!
      try { 
        xmlOutputGenerator0.getSortedXml((Document) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.XmlOutputGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlOutputGenerator xmlOutputGenerator0 = new XmlOutputGenerator();
      PluginParameters pluginParameters0 = mock(PluginParameters.class, new ViolatedAssumptionAnswer());
      xmlOutputGenerator0.setup(pluginParameters0);
  }
}
