/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:22:54 GMT 2019
 */

package sortpom.wrapper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jdom.Element;
import org.junit.runner.RunWith;
import sortpom.wrapper.ElementSortOrderMap;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ElementSortOrderMap_ESTest extends ElementSortOrderMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      elementSortOrderMap0.addElement((Element) null, 5);
      int int0 = elementSortOrderMap0.getSortOrder((Element) null);
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      elementSortOrderMap0.addElement((Element) null, (-110));
      int int0 = elementSortOrderMap0.getSortOrder((Element) null);
      assertEquals((-110), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      elementSortOrderMap0.addElement((Element) null, (-110));
      boolean boolean0 = elementSortOrderMap0.containsElement((Element) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      boolean boolean0 = elementSortOrderMap0.containsElement((Element) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      Element element0 = new Element("sortpom.wrapper.ElementSortOrderMap");
      // Undeclared exception!
      try { 
        elementSortOrderMap0.getSortOrder(element0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.ElementSortOrderMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ElementSortOrderMap elementSortOrderMap0 = new ElementSortOrderMap();
      Element element0 = new Element("sortpom.wrapper.ElementSortOrderMap");
      elementSortOrderMap0.addElement(element0, 0);
      int int0 = elementSortOrderMap0.getSortOrder(element0);
      assertEquals(0, int0);
  }
}
