/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Mar 13 11:15:02 GMT 2019
 */

package sortpom.wrapper;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class TextWrapperCreator_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sortpom.wrapper.TextWrapperCreator"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Jan\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "DE"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Jan\\Documents\\sortpom\\sorter"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Jan"); 
    java.lang.System.setProperty("user.language", "de"); 
    java.lang.System.setProperty("user.name", "Jan"); 
    java.lang.System.setProperty("user.timezone", ""); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TextWrapperCreator_ESTest_scaffolding.class.getClassLoader() ,
      "org.jdom.filter.Filter",
      "org.jdom.Comment",
      "sortpom.wrapper.content.SingleNewlineInTextWrapper",
      "sortpom.parameter.LineSeparatorUtil",
      "org.jdom.Content",
      "sortpom.jdomcontent.NewlineText",
      "org.jdom.CDATA",
      "org.jdom.Document",
      "org.jdom.JDOMException",
      "org.jdom.DocType",
      "sortpom.wrapper.content.Wrapper",
      "org.jdom.Verifier",
      "org.jdom.Namespace",
      "org.jdom.IllegalNameException",
      "org.jdom.NamespaceKey",
      "sortpom.parameter.DependencySortOrder",
      "org.jdom.ProcessingInstruction",
      "org.jdom.DataConversionException",
      "org.jdom.IllegalDataException",
      "sortpom.exception.FailureException",
      "org.jdom.Text",
      "sortpom.wrapper.TextWrapperCreator",
      "org.jdom.Attribute",
      "org.jdom.Parent",
      "sortpom.parameter.PluginParameters$1",
      "sortpom.parameter.PluginParameters$Builder",
      "org.jdom.IllegalTargetException",
      "sortpom.parameter.VerifyFailType",
      "org.jdom.IllegalAddException",
      "sortpom.wrapper.content.UnsortedWrapper",
      "org.jdom.Element",
      "sortpom.parameter.PluginParameters"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("sortpom.parameter.PluginParameters", false, TextWrapperCreator_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TextWrapperCreator_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sortpom.wrapper.TextWrapperCreator",
      "sortpom.wrapper.content.SingleNewlineInTextWrapper",
      "sortpom.parameter.PluginParameters",
      "org.jdom.Content",
      "org.jdom.Text",
      "org.jdom.Verifier",
      "org.jdom.CDATA",
      "sortpom.wrapper.content.UnsortedWrapper",
      "org.jdom.IllegalDataException",
      "org.jdom.Comment",
      "sortpom.jdomcontent.NewlineText"
    );
  }
}
