/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:32:12 GMT 2019
 */

package sortpom.wrapper.operation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jdom.Content;
import org.jdom.Element;
import org.junit.runner.RunWith;
import sortpom.wrapper.content.Wrapper;
import sortpom.wrapper.operation.DetachOperation;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DetachOperation_ESTest extends DetachOperation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DetachOperation detachOperation0 = new DetachOperation();
      Content content0 = mock(Content.class, new ViolatedAssumptionAnswer());
      doReturn((Content) null).when(content0).detach();
      Wrapper<Content> wrapper0 = (Wrapper<Content>) mock(Wrapper.class, new ViolatedAssumptionAnswer());
      doReturn(content0).when(wrapper0).getContent();
      detachOperation0.processOtherContent(wrapper0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DetachOperation detachOperation0 = new DetachOperation();
      Element element0 = mock(Element.class, new ViolatedAssumptionAnswer());
      doReturn((Content) null).when(element0).detach();
      doReturn((List) null).when(element0).removeContent();
      Wrapper<Element> wrapper0 = (Wrapper<Element>) mock(Wrapper.class, new ViolatedAssumptionAnswer());
      doReturn(element0).when(wrapper0).getContent();
      detachOperation0.processElement(wrapper0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DetachOperation detachOperation0 = new DetachOperation();
      Wrapper<Content> wrapper0 = (Wrapper<Content>) mock(Wrapper.class, new ViolatedAssumptionAnswer());
      doReturn((Content) null).when(wrapper0).getContent();
      // Undeclared exception!
      try { 
        detachOperation0.processOtherContent(wrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.operation.DetachOperation", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DetachOperation detachOperation0 = new DetachOperation();
      Wrapper<Element> wrapper0 = (Wrapper<Element>) mock(Wrapper.class, new ViolatedAssumptionAnswer());
      doReturn((Content) null).when(wrapper0).getContent();
      // Undeclared exception!
      try { 
        detachOperation0.processElement(wrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.operation.DetachOperation", e);
      }
  }
}
