/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Mar 13 11:28:23 GMT 2019
 */

package sortpom;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class XmlProcessor_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sortpom.XmlProcessor"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Jan\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "DE"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Jan\\Documents\\sortpom\\sorter"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Jan"); 
    java.lang.System.setProperty("user.language", "de"); 
    java.lang.System.setProperty("user.name", "Jan"); 
    java.lang.System.setProperty("user.timezone", ""); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(XmlProcessor_ESTest_scaffolding.class.getClassLoader() ,
      "sortpom.util.FileUtil",
      "org.jdom.filter.Filter",
      "org.jdom.input.SAXBuilder",
      "org.jdom.Comment",
      "sortpom.wrapper.operation.HierarchyWrapper",
      "sortpom.wrapper.operation.HierarchyRootWrapper",
      "sortpom.util.XmlOrderedResult",
      "sortpom.wrapper.operation.WrapperFactory",
      "org.jdom.Content",
      "sortpom.jdomcontent.NewlineText",
      "org.jdom.CDATA",
      "org.jdom.Document",
      "org.jdom.JDOMException",
      "sortpom.XmlProcessor",
      "org.jdom.DefaultJDOMFactory",
      "org.jdom.DocType",
      "sortpom.verify.ElementComparator",
      "sortpom.wrapper.content.Wrapper",
      "org.jdom.input.TextBuffer",
      "org.jdom.JDOMFactory",
      "org.jdom.ProcessingInstruction",
      "sortpom.wrapper.ElementSortOrderMap",
      "org.jdom.input.JAXPParserFactory",
      "org.jdom.input.BuilderErrorHandler",
      "sortpom.exception.FailureException",
      "sortpom.wrapper.WrapperFactoryImpl",
      "org.jdom.Text",
      "sortpom.wrapper.TextWrapperCreator",
      "org.jdom.EntityRef",
      "org.jdom.Parent",
      "org.jdom.input.JDOMParseException",
      "org.jdom.input.SAXHandler",
      "org.jdom.ContentList",
      "org.jdom.IllegalAddException",
      "org.jdom.Element",
      "sortpom.parameter.PluginParameters",
      "sortpom.wrapper.ElementWrapperCreator"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.Enumeration", false, XmlProcessor_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(XmlProcessor_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sortpom.XmlProcessor",
      "sortpom.util.FileUtil",
      "sortpom.wrapper.WrapperFactoryImpl",
      "sortpom.wrapper.ElementSortOrderMap",
      "sortpom.wrapper.ElementWrapperCreator",
      "sortpom.wrapper.TextWrapperCreator",
      "org.jdom.Content",
      "org.jdom.Element",
      "org.jdom.NamespaceKey",
      "org.jdom.Namespace",
      "org.jdom.Verifier",
      "org.jdom.AttributeList",
      "org.jdom.ContentList",
      "org.jdom.IllegalNameException",
      "org.apache.commons.io.output.StringBuilderWriter",
      "org.apache.commons.io.IOUtils",
      "org.apache.commons.io.Charsets",
      "sortpom.parameter.PluginParameters",
      "sortpom.verify.ElementComparator",
      "org.jdom.input.SAXBuilder",
      "org.jdom.DefaultJDOMFactory",
      "org.jdom.input.SAXHandler",
      "org.jdom.input.TextBuffer",
      "org.jdom.Document",
      "org.jdom.input.JAXPParserFactory",
      "org.jdom.input.BuilderErrorHandler",
      "org.jdom.JDOMException",
      "org.jdom.input.JDOMParseException",
      "org.jdom.EntityRef",
      "org.jdom.Attribute",
      "org.jdom.Text",
      "sortpom.wrapper.content.UnsortedWrapper",
      "org.jdom.IllegalDataException"
    );
  }
}
