/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:20:51 GMT 2019
 */

package sortpom.wrapper.operation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jdom.Content;
import org.jdom.Element;
import org.junit.runner.RunWith;
import sortpom.wrapper.content.DependencySortedWrapper;
import sortpom.wrapper.content.ModuleSortedWrapper;
import sortpom.wrapper.content.SingleNewlineInTextWrapper;
import sortpom.wrapper.content.UnsortedWrapper;
import sortpom.wrapper.content.Wrapper;
import sortpom.wrapper.operation.GetContentStructureOperation;
import sortpom.wrapper.operation.HierarchyWrapperOperation;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetContentStructureOperation_ESTest extends GetContentStructureOperation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetContentStructureOperation getContentStructureOperation0 = new GetContentStructureOperation();
      Element element0 = new Element("sortpom.wrapper.operation.GetContentStructureOperation");
      DependencySortedWrapper dependencySortedWrapper0 = new DependencySortedWrapper(element0, 0);
      getContentStructureOperation0.processElement(dependencySortedWrapper0);
      HierarchyWrapperOperation hierarchyWrapperOperation0 = getContentStructureOperation0.createSubOperation();
      UnsortedWrapper<Content> unsortedWrapper0 = new UnsortedWrapper<Content>(element0);
      // Undeclared exception!
      try { 
        hierarchyWrapperOperation0.processOtherContent(unsortedWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The Element cannot be added to itself
         //
         verifyException("org.jdom.ContentList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GetContentStructureOperation getContentStructureOperation0 = new GetContentStructureOperation();
      Element element0 = new Element("sortpom.wrapper.operation.GetContentStructureOperation");
      DependencySortedWrapper dependencySortedWrapper0 = new DependencySortedWrapper(element0, 0);
      getContentStructureOperation0.processElement(dependencySortedWrapper0);
      HierarchyWrapperOperation hierarchyWrapperOperation0 = getContentStructureOperation0.createSubOperation();
      // Undeclared exception!
      try { 
        hierarchyWrapperOperation0.processOtherContent((Wrapper<Content>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.operation.GetContentStructureOperation", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GetContentStructureOperation getContentStructureOperation0 = new GetContentStructureOperation();
      // Undeclared exception!
      try { 
        getContentStructureOperation0.processElement((Wrapper<Element>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.operation.GetContentStructureOperation", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GetContentStructureOperation getContentStructureOperation0 = new GetContentStructureOperation();
      Element element0 = new Element("x", "x", "x");
      ModuleSortedWrapper moduleSortedWrapper0 = new ModuleSortedWrapper(element0, 544);
      getContentStructureOperation0.processElement(moduleSortedWrapper0);
      HierarchyWrapperOperation hierarchyWrapperOperation0 = getContentStructureOperation0.createSubOperation();
      // Undeclared exception!
      try { 
        hierarchyWrapperOperation0.processElement(moduleSortedWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The Element cannot be added to itself
         //
         verifyException("org.jdom.ContentList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GetContentStructureOperation getContentStructureOperation0 = new GetContentStructureOperation();
      Element element0 = new Element("M", "M");
      ModuleSortedWrapper moduleSortedWrapper0 = new ModuleSortedWrapper(element0, 0);
      getContentStructureOperation0.processElement(moduleSortedWrapper0);
      SingleNewlineInTextWrapper singleNewlineInTextWrapper0 = SingleNewlineInTextWrapper.INSTANCE;
      HierarchyWrapperOperation hierarchyWrapperOperation0 = getContentStructureOperation0.createSubOperation();
      // Undeclared exception!
      try { 
        hierarchyWrapperOperation0.processOtherContent(singleNewlineInTextWrapper0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.content.SingleNewlineInTextWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GetContentStructureOperation getContentStructureOperation0 = new GetContentStructureOperation();
      SingleNewlineInTextWrapper singleNewlineInTextWrapper0 = SingleNewlineInTextWrapper.INSTANCE;
      getContentStructureOperation0.processOtherContent(singleNewlineInTextWrapper0);
      assertEquals("SingleNewlineInTextWrapper", singleNewlineInTextWrapper0.toString());
  }
}
