/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 10:54:35 GMT 2019
 */

package sortpom.wrapper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jdom.Comment;
import org.jdom.Element;
import org.jdom.Text;
import org.junit.runner.RunWith;
import sortpom.parameter.PluginParameters;
import sortpom.util.FileUtil;
import sortpom.wrapper.WrapperFactoryImpl;
import sortpom.wrapper.content.Wrapper;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WrapperFactoryImpl_ESTest extends WrapperFactoryImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      // Undeclared exception!
      try { 
        wrapperFactoryImpl0.setup((PluginParameters) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.ElementWrapperCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      // Undeclared exception!
      try { 
        wrapperFactoryImpl0.createDocumentFromDefaultSortOrderFile();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      Text text0 = new Text((String) null);
      Wrapper<Text> wrapper0 = wrapperFactoryImpl0.create(text0);
      assertNotNull(wrapper0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      Comment comment0 = new Comment("sortpm.apper.rapeFactoryIp");
      Wrapper<Comment> wrapper0 = wrapperFactoryImpl0.create(comment0);
      assertFalse(wrapper0.isSortable());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      Element element0 = new Element("sortpm.apper.rapeFactoryIp", "sortpm.apper.rapeFactoryIp", "sortpm.apper.rapeFactoryIp");
      Wrapper<Element> wrapper0 = wrapperFactoryImpl0.create(element0);
      assertTrue(wrapper0.isContentElement());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      Wrapper<Element> wrapper0 = wrapperFactoryImpl0.create((Element) null);
      assertFalse(wrapper0.isSortable());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      // Undeclared exception!
      try { 
        wrapperFactoryImpl0.createFromRootElement((Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      PluginParameters pluginParameters0 = mock(PluginParameters.class, new ViolatedAssumptionAnswer());
      wrapperFactoryImpl0.setup(pluginParameters0);
  }
}
