/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:40:34 GMT 2019
 */

package sortpom;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.maven.plugin.MojoFailureException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sortpom.SortMojo;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SortMojo_ESTest extends SortMojo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SortMojo sortMojo0 = new SortMojo();
      sortMojo0.lineSeparator = "";
      try { 
        sortMojo0.setup();
        fail("Expecting exception: MojoFailureException");
      
      } catch(MojoFailureException e) {
         //
         // LineSeparator must be either \\n, \\r or \\r\\n, but separator characters were []
         //
         verifyException("sortpom.exception.ExceptionConverter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SortMojo sortMojo0 = new SortMojo();
      // Undeclared exception!
      try { 
        sortMojo0.sortPom();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.SortPomImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SortMojo sortMojo0 = new SortMojo();
      // Undeclared exception!
      try { 
        sortMojo0.setup();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.parameter.LineSeparatorUtil", e);
      }
  }
}
