/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:27:16 GMT 2019
 */

package sortpom.jdomcontent;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sortpom.jdomcontent.NewlineText;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NewlineText_ESTest extends NewlineText_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NewlineText newlineText0 = new NewlineText();
      String string0 = newlineText0.toString();
      assertEquals("[NewLine]", string0);
  }
}
