/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:19:42 GMT 2019
 */

package sortpom.wrapper.content;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jdom.Element;
import org.junit.runner.RunWith;
import sortpom.wrapper.content.ModuleSortedWrapper;
import sortpom.wrapper.content.SortedWrapper;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ModuleSortedWrapper_ESTest extends ModuleSortedWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Element element0 = new Element("GROUPID", "GROUPID", "GROUPID");
      ModuleSortedWrapper moduleSortedWrapper0 = new ModuleSortedWrapper(element0, 658);
      element0.setText("5cA!fW3S6;d&-Dc{nTL");
      ModuleSortedWrapper moduleSortedWrapper1 = new ModuleSortedWrapper(element0, 658);
      boolean boolean0 = moduleSortedWrapper0.isBefore(moduleSortedWrapper1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Element element0 = new Element("GROUPID", "GROUPID", "GROUPID");
      ModuleSortedWrapper moduleSortedWrapper0 = new ModuleSortedWrapper(element0, 658);
      ModuleSortedWrapper moduleSortedWrapper1 = new ModuleSortedWrapper(element0, 658);
      boolean boolean0 = moduleSortedWrapper0.isBefore(moduleSortedWrapper1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Element element0 = new Element("GROUPID", "GROUPID");
      ModuleSortedWrapper moduleSortedWrapper0 = new ModuleSortedWrapper(element0, 673);
      SortedWrapper sortedWrapper0 = new SortedWrapper(element0, 673);
      boolean boolean0 = moduleSortedWrapper0.isBefore(sortedWrapper0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ModuleSortedWrapper moduleSortedWrapper0 = null;
      try {
        moduleSortedWrapper0 = new ModuleSortedWrapper((Element) null, (-2624));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.content.ModuleSortedWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Element element0 = new Element("GROUPID", "GROUPID", "GROUPID");
      ModuleSortedWrapper moduleSortedWrapper0 = new ModuleSortedWrapper(element0, 658);
      String string0 = moduleSortedWrapper0.toString();
      assertEquals("ModuleSortedWrapper{content=[Element: <GROUPID:GROUPID [Namespace: GROUPID]/>]}", string0);
  }
}
