/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:40:55 GMT 2019
 */

package sortpom.logger;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.maven.plugin.logging.Log;
import org.apache.maven.plugin.logging.SystemStreamLog;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sortpom.logger.MavenLogger;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MavenLogger_ESTest extends MavenLogger_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemStreamLog systemStreamLog0 = new SystemStreamLog();
      MavenLogger mavenLogger0 = new MavenLogger(systemStreamLog0);
      mavenLogger0.warn("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SystemStreamLog systemStreamLog0 = new SystemStreamLog();
      MavenLogger mavenLogger0 = new MavenLogger(systemStreamLog0);
      // Undeclared exception!
      try { 
        mavenLogger0.info((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.maven.plugin.logging.SystemStreamLog", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SystemStreamLog systemStreamLog0 = new SystemStreamLog();
      MavenLogger mavenLogger0 = new MavenLogger(systemStreamLog0);
      mavenLogger0.error("");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SystemStreamLog systemStreamLog0 = new SystemStreamLog();
      MavenLogger mavenLogger0 = new MavenLogger(systemStreamLog0);
      mavenLogger0.info("$p[,,~+$*}wU{T");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SystemStreamLog systemStreamLog0 = new SystemStreamLog();
      MavenLogger mavenLogger0 = new MavenLogger(systemStreamLog0);
      // Undeclared exception!
      try { 
        mavenLogger0.warn((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.maven.plugin.logging.SystemStreamLog", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MavenLogger mavenLogger0 = new MavenLogger((Log) null);
      // Undeclared exception!
      try { 
        mavenLogger0.error("Az6wPN~+k");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.logger.MavenLogger", e);
      }
  }
}
