/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:24:44 GMT 2019
 */

package sortpom.wrapper.content;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jdom.CDATA;
import org.jdom.Element;
import org.junit.runner.RunWith;
import sortpom.parameter.DependencySortOrder;
import sortpom.wrapper.content.PluginSortedWrapper;
import sortpom.wrapper.content.UnsortedWrapper;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PluginSortedWrapper_ESTest extends PluginSortedWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PluginSortedWrapper pluginSortedWrapper0 = new PluginSortedWrapper((Element) null, (-65));
      PluginSortedWrapper pluginSortedWrapper1 = new PluginSortedWrapper((Element) null, (-65));
      boolean boolean0 = pluginSortedWrapper0.isBefore(pluginSortedWrapper1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PluginSortedWrapper pluginSortedWrapper0 = new PluginSortedWrapper((Element) null, 0);
      DependencySortOrder dependencySortOrder0 = new DependencySortOrder("4$8}=Xcd&");
      // Undeclared exception!
      try { 
        pluginSortedWrapper0.setSortOrder(dependencySortOrder0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.content.PluginSortedWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Element element0 = new Element("sortpom.wrapper.content.PluginSortedWrapper", "sortpom.wrapper.content.PluginSortedWrapper");
      PluginSortedWrapper pluginSortedWrapper0 = new PluginSortedWrapper(element0, 241);
      CDATA cDATA0 = new CDATA("sortpom.wrapper.content.PluginSortedWrapper");
      UnsortedWrapper<CDATA> unsortedWrapper0 = new UnsortedWrapper<CDATA>(cDATA0);
      boolean boolean0 = pluginSortedWrapper0.isBefore(unsortedWrapper0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Element element0 = new Element("sortpom.wrapper.content.PluginSortedWrapper", "sortpom.wrapper.content.PluginSortedWrapper");
      PluginSortedWrapper pluginSortedWrapper0 = new PluginSortedWrapper(element0, 241);
      DependencySortOrder dependencySortOrder0 = new DependencySortOrder("sortpom.wrapper.content.PluginSortedWrapper");
      pluginSortedWrapper0.setSortOrder(dependencySortOrder0);
      assertFalse(dependencySortOrder0.isDeprecatedValueFalse());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Element element0 = new Element("sortpom.wrapper.content.PluginSortedWrapper", "sortpom.wrapper.content.PluginSortedWrapper");
      PluginSortedWrapper pluginSortedWrapper0 = new PluginSortedWrapper(element0, 241);
      String string0 = pluginSortedWrapper0.toString();
      assertEquals("PluginSortedWrapper{childElementSorter=ChildElementSorter{childElementTexts=[]}}", string0);
  }
}
