/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:13:48 GMT 2019
 */

package sortpom.wrapper.content;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jdom.Content;
import org.jdom.Element;
import org.jdom.Namespace;
import org.junit.runner.RunWith;
import sortpom.wrapper.content.ModuleSortedWrapper;
import sortpom.wrapper.content.SortedWrapper;
import sortpom.wrapper.content.Wrapper;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SortedWrapper_ESTest extends SortedWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SortedWrapper sortedWrapper0 = new SortedWrapper((Element) null, 10);
      SortedWrapper sortedWrapper1 = new SortedWrapper((Element) null, 5);
      boolean boolean0 = sortedWrapper0.isBefore(sortedWrapper1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Namespace namespace0 = Namespace.getNamespace("namespace");
      Element element0 = new Element("sortpom.wrapper.content.PluginSortedWrapper", namespace0);
      ModuleSortedWrapper moduleSortedWrapper0 = new ModuleSortedWrapper(element0, 2190);
      Element element1 = moduleSortedWrapper0.getContent();
      assertEquals("", element1.getNamespacePrefix());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SortedWrapper sortedWrapper0 = new SortedWrapper((Element) null, (-3338));
      SortedWrapper sortedWrapper1 = new SortedWrapper((Element) null, 5);
      boolean boolean0 = sortedWrapper0.isBefore(sortedWrapper1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SortedWrapper sortedWrapper0 = new SortedWrapper((Element) null, 10);
      boolean boolean0 = sortedWrapper0.isBefore(sortedWrapper0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SortedWrapper sortedWrapper0 = new SortedWrapper((Element) null, 10);
      boolean boolean0 = sortedWrapper0.isBefore((Wrapper<? extends Content>) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SortedWrapper sortedWrapper0 = new SortedWrapper((Element) null, 10);
      String string0 = sortedWrapper0.toString();
      assertEquals("SortedWrapper{element=null}", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SortedWrapper sortedWrapper0 = new SortedWrapper((Element) null, 10);
      Element element0 = sortedWrapper0.getContent();
      assertNull(element0);
  }
}
