/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:25:06 GMT 2019
 */

package sortpom.wrapper.operation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jdom.Element;
import org.junit.runner.RunWith;
import sortpom.util.FileUtil;
import sortpom.wrapper.WrapperFactoryImpl;
import sortpom.wrapper.content.DependencySortedWrapper;
import sortpom.wrapper.content.SortedWrapper;
import sortpom.wrapper.content.UnsortedWrapper;
import sortpom.wrapper.content.Wrapper;
import sortpom.wrapper.operation.HierarchyRootWrapper;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HierarchyRootWrapper_ESTest extends HierarchyRootWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Element element0 = new Element("I");
      SortedWrapper sortedWrapper0 = new SortedWrapper(element0, 0);
      HierarchyRootWrapper hierarchyRootWrapper0 = new HierarchyRootWrapper(sortedWrapper0);
      hierarchyRootWrapper0.detachStructure();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Element element0 = new Element("t", "t");
      UnsortedWrapper<Element> unsortedWrapper0 = new UnsortedWrapper<Element>(element0);
      HierarchyRootWrapper hierarchyRootWrapper0 = new HierarchyRootWrapper(unsortedWrapper0);
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      hierarchyRootWrapper0.createWrappedStructure(wrapperFactoryImpl0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UnsortedWrapper<Element> unsortedWrapper0 = new UnsortedWrapper<Element>((Element) null);
      HierarchyRootWrapper hierarchyRootWrapper0 = new HierarchyRootWrapper(unsortedWrapper0);
      Wrapper<Element> wrapper0 = hierarchyRootWrapper0.getElementContent();
      assertNull(wrapper0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HierarchyRootWrapper hierarchyRootWrapper0 = null;
      try {
        hierarchyRootWrapper0 = new HierarchyRootWrapper((Wrapper<Element>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.operation.HierarchyWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Element element0 = new Element("I");
      SortedWrapper sortedWrapper0 = new SortedWrapper(element0, 0);
      HierarchyRootWrapper hierarchyRootWrapper0 = new HierarchyRootWrapper(sortedWrapper0);
      Wrapper<Element> wrapper0 = hierarchyRootWrapper0.getElementContent();
      assertSame(sortedWrapper0, wrapper0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DependencySortedWrapper dependencySortedWrapper0 = new DependencySortedWrapper((Element) null, 970);
      HierarchyRootWrapper hierarchyRootWrapper0 = new HierarchyRootWrapper(dependencySortedWrapper0);
      hierarchyRootWrapper0.connectXmlStructure();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Element element0 = new Element("t", "t");
      UnsortedWrapper<Element> unsortedWrapper0 = new UnsortedWrapper<Element>(element0);
      HierarchyRootWrapper hierarchyRootWrapper0 = new HierarchyRootWrapper(unsortedWrapper0);
      hierarchyRootWrapper0.sortStructureAttributes();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DependencySortedWrapper dependencySortedWrapper0 = new DependencySortedWrapper((Element) null, 970);
      HierarchyRootWrapper hierarchyRootWrapper0 = new HierarchyRootWrapper(dependencySortedWrapper0);
      hierarchyRootWrapper0.sortStructureElements();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      DependencySortedWrapper dependencySortedWrapper0 = new DependencySortedWrapper((Element) null, 999);
      HierarchyRootWrapper hierarchyRootWrapper0 = new HierarchyRootWrapper(dependencySortedWrapper0);
      FileUtil fileUtil0 = new FileUtil();
      WrapperFactoryImpl wrapperFactoryImpl0 = new WrapperFactoryImpl(fileUtil0);
      // Undeclared exception!
      try { 
        hierarchyRootWrapper0.createWrappedStructure(wrapperFactoryImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.operation.HierarchyWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      DependencySortedWrapper dependencySortedWrapper0 = new DependencySortedWrapper((Element) null, 970);
      HierarchyRootWrapper hierarchyRootWrapper0 = new HierarchyRootWrapper(dependencySortedWrapper0);
      // Undeclared exception!
      try { 
        hierarchyRootWrapper0.detachStructure();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.wrapper.operation.DetachOperation", e);
      }
  }
}
