/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:04:24 GMT 2019
 */

package sortpom.parameter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sortpom.parameter.IndentCharacters;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IndentCharacters_ESTest extends IndentCharacters_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IndentCharacters indentCharacters0 = new IndentCharacters(255);
      String string0 = indentCharacters0.getIndentCharacters();
      assertEquals("                                                                                                                                                                                                                                                               ", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IndentCharacters indentCharacters0 = new IndentCharacters(1162);
      // Undeclared exception!
      try { 
        indentCharacters0.getIndentCharacters();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // nrOfIndentSpace cannot be below -1 or above 255, was: 1162
         //
         verifyException("sortpom.parameter.IndentCharacters", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IndentCharacters indentCharacters0 = new IndentCharacters(18);
      String string0 = indentCharacters0.getIndentCharacters();
      assertEquals("                  ", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IndentCharacters indentCharacters0 = new IndentCharacters((-2));
      // Undeclared exception!
      try { 
        indentCharacters0.getIndentCharacters();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // nrOfIndentSpace cannot be below -1 or above 255, was: -2
         //
         verifyException("sortpom.parameter.IndentCharacters", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IndentCharacters indentCharacters0 = new IndentCharacters(0);
      String string0 = indentCharacters0.getIndentCharacters();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      IndentCharacters indentCharacters0 = new IndentCharacters((-1));
      String string0 = indentCharacters0.getIndentCharacters();
      assertEquals("\t", string0);
  }
}
