/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:05:49 GMT 2019
 */

package sortpom.parameter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sortpom.parameter.LineSeparatorUtil;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LineSeparatorUtil_ESTest extends LineSeparatorUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LineSeparatorUtil lineSeparatorUtil0 = null;
      try {
        lineSeparatorUtil0 = new LineSeparatorUtil((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.parameter.LineSeparatorUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LineSeparatorUtil lineSeparatorUtil0 = new LineSeparatorUtil("\r\n");
      assertEquals("\r\n", lineSeparatorUtil0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LineSeparatorUtil lineSeparatorUtil0 = new LineSeparatorUtil("\n");
      assertEquals("\n", lineSeparatorUtil0.toString());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LineSeparatorUtil lineSeparatorUtil0 = null;
      try {
        lineSeparatorUtil0 = new LineSeparatorUtil(" ");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // LineSeparator must be either \\n, \\r or \\r\\n, but separator characters were [32]
         //
         verifyException("sortpom.parameter.LineSeparatorUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LineSeparatorUtil lineSeparatorUtil0 = new LineSeparatorUtil("\r");
      String string0 = lineSeparatorUtil0.toString();
      assertEquals("\r", string0);
  }
}
