/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:41:40 GMT 2019
 */

package sortpom;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.maven.plugin.MojoFailureException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sortpom.VerifyMojo;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VerifyMojo_ESTest extends VerifyMojo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VerifyMojo verifyMojo0 = new VerifyMojo();
      verifyMojo0.lineSeparator = "?Zu\"UY<8t2XAh3T0";
      try { 
        verifyMojo0.setup();
        fail("Expecting exception: MojoFailureException");
      
      } catch(MojoFailureException e) {
         //
         // LineSeparator must be either \\n, \\r or \\r\\n, but separator characters were [63, 90, 117, 34, 85, 89, 60, 56, 116, 50, 88, 65, 104, 51, 84, 48]
         //
         verifyException("sortpom.exception.ExceptionConverter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VerifyMojo verifyMojo0 = new VerifyMojo();
      // Undeclared exception!
      try { 
        verifyMojo0.sortPom();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.SortPomImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      VerifyMojo verifyMojo0 = new VerifyMojo();
      // Undeclared exception!
      try { 
        verifyMojo0.setup();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortpom.parameter.LineSeparatorUtil", e);
      }
  }
}
