/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 13 11:31:41 GMT 2019
 */

package sortpom.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.MalformedURLException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sortpom.util.UrlWrapper;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UrlWrapper_ESTest extends UrlWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UrlWrapper urlWrapper0 = new UrlWrapper("");
      try { 
        urlWrapper0.openStream();
        fail("Expecting exception: MalformedURLException");
      
      } catch(MalformedURLException e) {
         //
         // no protocol: 
         //
         verifyException("java.net.URL", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UrlWrapper urlWrapper0 = new UrlWrapper("");
      boolean boolean0 = urlWrapper0.isUrl();
      assertFalse(boolean0);
  }
}
